In [ ]:
import pandas as pd

movies = pd.read_csv("/Users/erickvanscoit/Github/K-neighbors/data/tmdb_5000_moviesk_near.csv")
credits = pd.read_csv("/Users/erickvanscoit/Github/K-neighbors/data/tmdb_5000_moviesk_near.csv")



# Display the first few rows of the movies DataFrame
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [10]:
credits.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [11]:
import sqlite3

conn = sqlite3.connect("../data/movies_database.db")

movies.to_sql("movies_table", conn, if_exists = "replace", index = False)
credits.to_sql("credits_table", conn, if_exists = "replace", index = False)

4803

In [12]:
query = """
    SELECT *
    FROM movies_table
    INNER JOIN credits_table
    ON movies_table.title = credits_table.title;
"""

total_data = pd.read_sql_query(query, conn)
conn.close()

total_data = total_data.loc[:, ~total_data.columns.duplicated()]
total_data.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [33]:
import pandas as pd
import json
from sklearn.preprocessing import MultiLabelBinarizer

# Función para manejar errores de JSON
def load_json_safe(json_str, default_value=None):
    try:
        return json.loads(json_str)
    except (TypeError, json.JSONDecodeError):
        return default_value

# Cargar el DataFrame desde el archivo CSV
file_path = "/Users/erickvanscoit/Github/K-neighbors/data/tmdb_5000_moviesk_near.csv"
total_data = pd.read_csv(file_path)

# Verificar columnas disponibles
print("Columnas disponibles en el DataFrame:")
print(total_data.columns)

# Procesar la columna "genres"
if "genres" in total_data.columns:
    total_data["genres"] = total_data["genres"].apply(
        lambda x: [item["name"] for item in load_json_safe(x, default_value=[])] if pd.notna(x) and isinstance(x, str) else None
    )
else:
    print("La columna 'genres' no está disponible en el DataFrame.")

# Procesar la columna "keywords"
if "keywords" in total_data.columns:
    total_data["keywords"] = total_data["keywords"].apply(
        lambda x: [item["name"] for item in load_json_safe(x, default_value=[])] if pd.notna(x) and isinstance(x, str) else None
    )
else:
    print("La columna 'keywords' no está disponible en el DataFrame.")

# Procesar otras columnas como "production_companies" y "production_countries" si están en formato JSON
if "production_companies" in total_data.columns:
    total_data["production_companies"] = total_data["production_companies"].apply(
        lambda x: [item["name"] for item in load_json_safe(x, default_value=[])] if pd.notna(x) and isinstance(x, str) else None
    )

if "production_countries" in total_data.columns:
    total_data["production_countries"] = total_data["production_countries"].apply(
        lambda x: [item["name"] for item in load_json_safe(x, default_value=[])] if pd.notna(x) and isinstance(x, str) else None
    )

# Codificar los géneros con One-Hot Encoding para análisis
if "genres" in total_data.columns:
    mlb = MultiLabelBinarizer()
    genre_encoded = mlb.fit_transform(total_data["genres"].dropna())
    genre_labels = mlb.classes_

    # Crear un DataFrame con los géneros codificados
    genre_df = pd.DataFrame(genre_encoded, columns=genre_labels)
    total_data = pd.concat([total_data.reset_index(drop=True), genre_df.reset_index(drop=True)], axis=1)

    print("Géneros codificados (primeras filas):")
    print(genre_df.head())
else:
    print("No se codificaron los géneros, columna no encontrada.")

# Ver las primeras filas del DataFrame procesado
print("Primeras filas del DataFrame procesado:")
print(total_data.head())

Columnas disponibles en el DataFrame:
Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')
Géneros codificados (primeras filas):
   Action  Adventure  Animation  Comedy  Crime  Documentary  Drama  Family  \
0       1          1          0       0      0            0      0       0
1       1          1          0       0      0            0      0       0
2       1          1          0       0      1            0      0       0
3       1          0          0       0      1            0      1       0
4       1          1          0       0      0            0      0       0

   Fantasy  Foreign  History  Horror  Music  Mystery  Romance  \
0        1        0        0       0      0        0        0
1        1        0        0       0      0        0        0
2        0        0        0       0      0        0        0
3        0        0        0       0      0        0        0
4        0        0        0       0      0        0        0

   Science Fiction  TV Movie  Thriller  War  Western
0                1         0         0    0        0
1                0         0         0    0        0
2                0         0         0    0        0
3                0         0         1    0        0
4                1         0         0    0        0
Primeras filas del DataFrame procesado:
      budget                                         genres  \
0  237000000  [Action, Adventure, Fantasy, Science Fiction]
1  300000000                   [Adventure, Fantasy, Action]
2  245000000                     [Action, Adventure, Crime]
3  250000000               [Action, Crime, Drama, Thriller]
4  260000000           [Action, Adventure, Science Fiction]

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995
1  http://disney.go.com/disneypictures/pirates/     285
2   http://www.sonypictures.com/movies/spectre/  206647
3            http://www.thedarkknightrises.com/   49026
4          http://movies.disney.com/john-carter   49529

                                            keywords original_language  \
0  [culture clash, future, space war, space colon...                en
1  [ocean, drug abuse, exotic island, east india ...                en
2  [spy, based on novel, secret agent, sequel, mi...                en
3  [dc comics, crime fighter, terrorist, secret i...                en
4  [based on novel, mars, medallion, space travel...                en

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577
1  Captain Barbossa, long believed to be dead, ha...  139.082615
2  A cryptic message from Bond’s past sends him o...  107.376788
3  Following the death of District Attorney Harve...  112.312950
4  John Carter is a war-weary, former military ca...   43.926995

                                production_companies  ... History Horror  \
0  [Ingenious Film Partners, Twentieth Century Fo...  ...       0      0
1  [Walt Disney Pictures, Jerry Bruckheimer Films...  ...       0      0
2                   [Columbia Pictures, Danjaq, B24]  ...       0      0
3  [Legendary Pictures, Warner Bros., DC Entertai...  ...       0      0
4                             [Walt Disney Pictures]  ...       0      0

   Music  Mystery Romance Science Fiction TV Movie Thriller  War  Western
0      0        0       0               1        0        0    0        0
1      0        0       0               0        0        0    0        0
2      0        0       0               0        0        0    0        0
3      0        0       0               0        0        1    0        0
4      0        0       0               1        0        0    0        0

[5 rows x 40 columns]

In [34]:
print(total_data[["genres", "keywords", "production_companies", "production_countries"]].head())
# Guardar el DataFrame procesado en un nuevo archivo CSV

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]
1                   [Adventure, Fantasy, Action]
2                     [Action, Adventure, Crime]
3               [Action, Crime, Drama, Thriller]
4           [Action, Adventure, Science Fiction]

                                            keywords  \
0  [culture clash, future, space war, space colon...
1  [ocean, drug abuse, exotic island, east india ...
2  [spy, based on novel, secret agent, sequel, mi...
3  [dc comics, crime fighter, terrorist, secret i...
4  [based on novel, mars, medallion, space travel...

                                production_companies  \
0  [Ingenious Film Partners, Twentieth Century Fo...
1  [Walt Disney Pictures, Jerry Bruckheimer Films...
2                   [Columbia Pictures, Danjaq, B24]
3  [Legendary Pictures, Warner Bros., DC Entertai...
4                             [Walt Disney Pictures]

                         production_countries
0  [United States of America, United Kingdom]
1                  [United States of America]
2  [United Kingdom, United States of America]
3                  [United States of America]
4                  [United States of America]

In [37]:

total_data["genres"] = total_data["genres"].apply(lambda x: [str(genre) for genre in x])
total_data["keywords"] = total_data["keywords"].apply(lambda x: [str(keyword) for keyword in x])
total_data["production_companies"] = total_data["production_companies"].apply(lambda x: [str(actor) for actor in x])
total_data["production_countries"] = total_data["production_countries"].apply(lambda x: [str(crew_member) for crew_member in x])

total_data["tags"] = total_data["genres"] + total_data["keywords"] + total_data["production_companies"] + total_data["production_countries"]
total_data["tags"] = total_data["tags"].apply(lambda x: ",".join(x).replace(",", " "))

columns_to_drop = ["genres", "keywords", "production_companies", "production_countries"]
existing_columns_to_drop = [col for col in columns_to_drop if col in total_data.columns]
total_data.drop(columns=existing_columns_to_drop, inplace=True)

total_data.iloc[0].tags

'Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d Ingenious Film Partners Twentieth Century Fox Film Corporation Dune Entertainment Lightstorm Entertainment United States of America United Kingdom'

In [38]:
total_data.to_csv("../data/processed/clean_data.csv", index = False)

conn = sqlite3.connect("../data/movies_database.db")

movies.to_sql("clean_movies_data", conn, if_exists = "replace", index = False)

4803

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(total_data["tags"])

model = NearestNeighbors(n_neighbors = 6, algorithm = "brute", metric = "cosine")
model.fit(tfidf_matrix)

def get_movie_recommendations(movie_title):
    movie_index = total_data[total_data["title"] == movie_title].index[0]
    distances, indices = model.kneighbors(tfidf_matrix[movie_index])
    similar_movies = [(total_data["title"][i], distances[0][j]) for j, i in enumerate(indices[0])]
    return similar_movies[1:]

input_movie = "Avatar"
recommendations = get_movie_recommendations(input_movie)
print("Film recommendations '{}'".format(input_movie))
for movie, distance in recommendations:
    print("- Film: {}".format(movie))

Film recommendations 'Avatar'
- Film: Alien³
- Film: Planet of the Apes
- Film: Aliens
- Film: Alien
- Film: Silent Running

In [40]:
from pickle import dump

dump(model, open("../models/knn_neighbors-.sav", "wb"))